language: node_js
node_js:
  - '8'
env:
  global:
    - CC_TEST_REPORTER_ID=1705ec8a309648977651f5eec4f745a6d52ee3206ff094359482b71cd106605e
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run lint
  - npm test
after_script:
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.json ./packages/feathers-dynamoose/coverage/lcov.info
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi
